time = ('Palmeiras', 'Gremio', 'Atlético MG', 'Flamengo', 'Botafogo', 'Bragantino ', 'Fluminense',
        'Atletico PR','Internacional', 'Fortaleza','São Paulo','Cuiaba','Corinthians', 'Cruzeiro',
        'Vasco','Bahia','santos','Goias','Coritiba','América MG')
print('+'*40)
print('='*7,'CAMPEONATO BRASILEIRO INFO', '='*7 )
print('+'*40)
print ('Times do Brasielrão 2023')
print(time)
print('-'*40)
print('Os 5 primeiros colocados')
print(time[:5])
print('-'*40)
print('Os 4 ultimos colocados')
print(time[-4:])
print('-'*40)
print ('Times em ordem alfabética')
print(sorted(time))
print('-'*40)
print('Em que posição o São Paulo Ficou ?')
print(f'O São Paulo ficou na {time.index('São Paulo') +1}º posição.')