n = input('DIGITE ALGO:')
print('O tipo primitivo dessa informação é:',type(n))
print('Essa informação é letra :',n.isalpha())
print('Essa informação é um numero:',n.isnumeric())
print('Só tem espaço?', n.isspace())
print('Tem casa decimal', n.isdecimal())
print('é alfanumerico?', n.isalnum())
print('Esta em maiuscula ?', n.isupper())
print('ESta em minuscula', n.islower())